name: Simple CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Test backend
      run: |
        cd back
        echo "Backend tests would run here"
        
    - name: Test frontend
      run: |
        cd front
        echo "Frontend tests would run here"
        
    - name: Build Docker images
      run: |
        docker-compose build